### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Cormoran96** [arminfelder/gridfsmigrate#16]
```
Traceback (most recent call last):
  File "./migrate.py", line 234, in <module>
    obj.dumpfiles("rocketchat_uploads", store)
  File "./migrate.py", line 111, in dumpfiles
    fileext = mime.guess_extension(res.content_type)
  File "/usr/lib/python3.7/mimetypes.py", line 191, in guess_extension
    extensions = self.guess_all_extensions(type, strict)
  File "/usr/lib/python3.7/mimetypes.py", line 170, in guess_all_extensions
    type = type.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```
Somebody have this issue or can help me ?

**Comment by Cormoran96** [comment]
If I understand correctly, it fail because mime don't find type of one file.

Is it correct? I think for a simple workaround it's to add a try: but I think to have a better solution.

**Comment by arminfelder** [comment]
@Cormoran96  I guess #17 solved the issue for you

**Comment by Cormoran96** [comment]
Indeed, this has been fixed
