### ISSUE TITLE
umlauts in filenames

### ISSUE THREAD

**Issue by sennewood** [arminfelder/gridfsmigrate#19]
We set `PYTHONIOENCODING=utf-8` as mentioned in the Readme.

But when the script computes the first file with an umlaut in the filename, in our case:
`14. Dumping 29sDGZSx79ozo6JWu Clipboard - 19. März 2020 15:39`

we got this error:

```Traceback (most recent call last):
  File "migrate.py", line 229, in <module>
    obj.dumpfiles("rocketchat_uploads", store)
  File "migrate.py", line 114, in dumpfiles
    key = store.put(filename, data, upload)
  File "migrate.py", line 45, in put
    file = open(self.outDir + "/" + filename, "wb")
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 48: ordinal not in range(128)```

**Comment by tamasgal** [comment]
Make sure you have set up your locales correctly, example via

```
update-locale en_US-UTF-8
```

verify with

```
locale
```

which should look something like this:

```
~# locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
