### ISSUE TITLE
gridfs.errors.CorruptGridFile: no chunk #0

### ISSUE THREAD

**Issue by xxzk** [arminfelder/gridfsmigrate#21]
Hello,

Executing the python script like below

```
python3 ./migrate.py -c dump -r rocketchat -t FileSystem -d /root/gridfs_dump/
```

And here is the return error.

```
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/gridfs/grid_file.py", line 755, in next
    chunk = self._next_with_retry()
  File "/usr/local/lib64/python3.6/site-packages/gridfs/grid_file.py", line 747, in _next_with_retry
    return self._cursor.next()
  File "/usr/local/lib64/python3.6/site-packages/pymongo/cursor.py", line 1215, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./migrate.py", line 229, in <module>
    obj.dumpfiles("rocketchat_uploads", store)
  File "./migrate.py", line 104, in dumpfiles
    data = res.read()
  File "/usr/local/lib64/python3.6/site-packages/gridfs/grid_file.py", line 565, in read
    chunk_data = self.readchunk()
  File "/usr/local/lib64/python3.6/site-packages/gridfs/grid_file.py", line 528, in readchunk
    chunk = self.__chunk_iter.next()
  File "/usr/local/lib64/python3.6/site-packages/gridfs/grid_file.py", line 759, in next
    raise CorruptGridFile("no chunk #%d" % self._next_chunk)
gridfs.errors.CorruptGridFile: no chunk #0
```

Thanks.

**Comment by xxzk** [comment]
Update infomation.

I dump the `rocketchat` database from MongoDB in docker container,and restore to another VM which installed MongoDB x86_64.
The restore progress done as well.
RocketChat version is v3.6.1 and MongoDB docker image version is 4.4.

**Comment by tamasgal** [comment]
It turned out to be a migration error, probably caused by RocketChat or so, no idea. If I run the dump on the original server with MongoDB 3.6, it works. If I run it on the already migrated backup under MongoDB 4.4.15, I get the corruption errors.
