### ISSUE TITLE
Not working with non English?

### ISSUE THREAD

**Issue by jungleran** [arminfelder/gridfsmigrate#7]
```
Traceback (most recent call last):
  File "./migrate.py", line 232, in <module>
    obj.dumpfiles("rocketchat_uploads", store)
  File "./migrate.py", line 116, in dumpfiles
    upload['name']))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-33: ordinal not in range(128)
```

**Comment by jungleran** [comment]
BTW, a dirty way to get it working, prepending `PYTHONIOENCODING=utf-8` to the commands

**Comment by jungleran** [comment]
PYTHONIOENCODING=utf-8 works with Chinese, but not working with Vietnamese according to my rocketchat installation.

**Comment by sennewood** [comment]
It doesn't work with german either (#19).

**Comment by tamasgal** [comment]
See https://github.com/arminfelder/gridfsmigrate/issues/19#issuecomment-1466268860
